name: Print Database Password

on:
  push:
    branches:
      - dev
      - main

jobs:
  print-password:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Database Password
        run: |
          if [ "$GITHUB_REF" == "refs/heads/dev" ]; then
            echo "Database Password (dev): $DATABASE_PASSWORD_DEV"
          elif [ "$GITHUB_REF" == "refs/heads/main" ]; then
            echo "Database Password (main): ${{env.DATABASE_PASSWORD_PRD}}"
          else
            echo "No matching branch found for printing database password. Exit"
          fi