name: Print Database Password

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  get-current-branch:
    runs-on: ubuntu-latest

    outputs:
      id: extract_branch
      set-env:
        branch: ${{ steps.extract_branch.outputs.branch }}

  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Database Password
        run: |
          echo ${{ vars.DATABASE_PASSWORD }} on ${{ steps.extract_branch.outputs.branch }}
        id: extract_branch