name: "Main"

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      DATABASE_PASSWORD_DEV: ${{ steps.setvars.outputs.DATABASE_PASSWORD_DEV }}
      phase: ${{ steps.setvars.outputs.phase }}

    steps:
      - name: Cancel previous workflow
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - name: Set variables
        id: setvars
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "::set-output name=DATABASE_PASSWORD_DEV::DATABASE_PASSWORD_DEV"
            echo "::set-output name=phase::staging"
          fi

          if [[ "${{github.base_ref}}" == "dev" || "${{github.ref}}" == "refs/heads/dev" ]]; then
            echo "::set-output name=DATABASE_PASSWORD_DEV::my-project-prd"
            echo "::set-output name=phase::dev"
          fi

  print:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Print
        run: echo "DATABASE_PASSWORD_DEV=${{needs.init.outputs.DATABASE_PASSWORD_DEV}}"
