name: Print Database Password

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    env:
        DATABASE_PASSWORD: $DATABASE_PASSWORD_DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Database Password
        run: |
          echo ${{ env.DATABASE_PASSWORD }}