name: Print Database Password

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  get-current-branch:
    runs-on: ubuntu-latest

    outputs:
      id: extract_branch
      set-env:
        branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

  deploy-dev:
    needs: get-current-branch
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Database Password
        run: |
          echo ${{ secrets.DATABASE_PASSWORD_DEV }} on ${{ needs.get-current-branch.outputs.branch }}
